{% set python_min = '3.10.0' %}
{% set name = "vet" %}
{% set version = "0.1.1.post4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vet-{{ version }}.tar.gz
  sha256: 22915579241cabbd429812c83287fc8867fa05e1c1cbbfdd8a9fbbc79582d565

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - poetry >=1.8.2,<2.0.0
    - msgspec >=0.18.6,<0.19.0
    - tomli-w >=1.0.0,<2.0.0
    - typing-extensions >=4.10.0,<5.0.0

test:
  imports:
    - vet
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/irgolic/vet
  summary: A poetry plugin for establishing chain of trust
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
